apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
{{- range $key, $value := .Values.sealedSecret.encryptedData }}
    {{ $key }}: {{ $value | quote }}
{{- end }}