apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterIP.name }}
spec:
  selector:
    app: {{ .Values.statefulset.name }}
  ports:
    - port: {{ .Values.statefulset.containerPort }}
      targetPort: {{ .Values.clusterIP.targetPort }}