statefulset:
  name: postgres
  replicas: '1'
  image:
    name: postgres
    tag: '16'
  containerPort: '5432'
  volumeMounts:
    mountPath: /var/lib/postgresql/data
    name: postgres-db
  limits:
    memory: 256Mi
    cpu: 500m
persistantVolume:
  name: postgres-pv
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  reclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 
    path: 
    readOnly: false
persistantVolumeClaim:
  name: postgres-pvc
  resources:
    requests:
      storage: 1Gi
clusterIP:
  name: postgres
  targetPort: '5432'
configMap:
  name: postgres-configmap
  data:
    PGDATA: /var/lib/postgresql/data/pgdata
sealedSecret:
  name: postgres-sealedsecret
  encryptedData:
    POSTGRES_DB: 
    POSTGRES_USER: 
    POSTGRES_PASSWORD: 