{{- $_ := set .Values "__count" 0 }}

{{- range .Values.manifests }}
{{- include "manifests.counter.inc" $ }}
{{- include "manifests.manifest" (dict
      "manifest" .
      "context" $
) }}
---
{{- end }}