apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.account.name }}
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.role.name }}
rules:
{{- range .Values.serviceAccount.role.rules }}
  - apiGroups: {{ toJson .apiGroups }}
    resources: {{ toJson .resources }}
    {{- if .resourceNames }}
    resourceNames: {{ toJson .resourceNames }}
    {{- end }}
    verbs: {{ toJson .verbs }}
{{- end }}

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.roleBinding.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.account.name }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.role.name }}
  apiGroup: ""